[package]
name = "framaschedule"
version = "0.2.0"
authors = ["Bennett Piater <bennett@piater.name>"]
edition = "2018"

[dependencies]
# import
csv = "1.0.5"
simple-error = "0.1.13"
scan_fmt = "0.1.3"

# CLI
clap = "2.32.0"

# parallelization
scoped_threadpool = "0.1.9"
num_cpus = "1.10.0"
